In [1]:
# Install the required libraries (if not already installed)
!pip install liac-arff pandas

Requirement already satisfied: liac-arff in c:\users\alkods\anaconda3\lib\site-packages (2.5.0)
Requirement already satisfied: pandas in c:\users\alkods\anaconda3\lib\site-packages (1.3.5)
Requirement already satisfied: numpy>=1.17.3; platform_machine != "aarch64" and platform_machine != "arm64" and python_version < "3.10" in c:\users\alkods\anaconda3\lib\site-packages (from pandas) (1.21.6)
Requirement already satisfied: pytz>=2017.3 in c:\users\alkods\anaconda3\lib\site-packages (from pandas) (2019.3)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\alkods\anaconda3\lib\site-packages (from pandas) (2.8.0)
Requirement already satisfied: six>=1.5 in c:\users\alkods\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas) (1.12.0)

In [3]:
# Import necessary libraries
from scipy.io import arff
import pandas as pd

In [4]:
# Load ARFF file using the 'arff' library
data, meta = arff.loadarff('E:/Asya/polish+companies+bankruptcy+data/4year.arff')

# Convert the loaded data to a Pandas DataFrame
df = pd.DataFrame(data)

# Display the number of rows in the DataFrame
print(len(df))

# Display the first few rows of the DataFrame
df.head()

9792

,Attr1,Attr2,Attr3,Attr4,Attr5,Attr6,Attr7,Attr8,Attr9,Attr10,...,Attr56,Attr57,Attr58,Attr59,Attr60,Attr61,Attr62,Attr63,Attr64,class
0,0.159290,0.46240,0.07773,1.1683,-44.853,0.467020,0.189480,0.82895,1.1223,0.38330,...,0.108990,0.41557,0.89101,0.001422,7.7928,4.9914,119.810,3.0465,3.0560,b'0'
1,-0.127430,0.46243,0.26917,1.7517,7.597,0.000925,-0.127430,1.16250,1.2944,0.53757,...,-0.089372,-0.23704,1.06250,0.150410,5.4327,3.4629,100.970,3.6150,3.4725,b'0'
2,0.070488,0.23570,0.52781,3.2393,125.680,0.163670,0.086895,2.87180,1.0574,0.67689,...,0.054286,0.10413,0.94571,0.000000,7.1070,3.3808,76.076,4.7978,4.7818,b'0'
3,0.136760,0.40538,0.31543,1.8705,19.115,0.504970,0.136760,1.45390,1.1144,0.58938,...,0.102630,0.23203,0.89737,0.073024,6.1384,4.2241,88.299,4.1337,4.6484,b'0'
4,-0.110080,0.69793,0.18878,1.2713,-15.344,0.000000,-0.110080,0.43282,1.7350,0.30207,...,0.439880,-0.36440,0.57153,0.000000,18.8010,2.7925,146.390,2.4934,15.0360,b'0'

In [6]:
# Rename the 'class' column to 'bankrupt'
df.rename(columns={'class': 'bankrupt'}, inplace=True)
# Convert values in the 'bankrupt' column from b'0' to False and b'1' to True
df['bankrupt'] = df['bankrupt'].replace({b'0': False, b'1': True})

# Display the count of unique values in the 'bankrupt' column (after conversion)
print(df["bankrupt"].value_counts())

False    9277
True      515
Name: bankrupt, dtype: int64

In [8]:
# Save the DataFrame to a CSV file
df.to_csv('bankruptcy_data.csv', index=False)

# Print a message to indicate that the CSV file has been saved
print("CSV file saved successfully.")

CSV file saved successfully.